### ISSUE TITLE
Performans Sorunu ve Test Talebi

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#38]
Bazı durumlarda iki kere response dönüyor gibi buraya sürekli istek gelirse bu hata caseleri performansı öldürür.
Kontrol edilip test edilmesi lazım. Backendi ayağa kaldırın tüm endpointlere istek atın  bu hata mesajlarında dönmüyor try catch içinde erroru console log olarak basmanız lazım enson ekleYardimKaydi  endpointinde gördüm.

hata mesajı 

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:393:5)
    at ServerResponse.setHeader (node:_http_outgoing:644:11)
    at ServerResponse.header (/Users/felix/Documents/deprem/deprem-io-backend/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/Users/felix/Documents/deprem/deprem-io-backend/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/Users/felix/Documents/deprem/deprem-io-backend/node_modules/express/lib/response.js:278:15)
    at /Users/felix/Documents/deprem/deprem-io-backend/routes/urls.js:625:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_HTTP_HEADERS_SENT'
}
```

**Comment by izzetemredemir** [comment]
Endpointlerin try catch kısmından şu şekilde  kontrol ediln

```
 .catch((error) => {
      console.log(error);
      res.status(500).json({
        message: "Yardim kaydi olusturulamadi.",
        error,
      });
    });
```

**Comment by izzetemredemir** [comment]
Response döndükten sonra kodun aşağı doğru çalışmaması gerek şuan alttaki satırlar da çalışıyor bundan emin olmamız lazım

**Comment by mehmetik** [comment]
Alan içinde res.status(500).send yapısı .json ile standartlaıştırıldı.

**Comment by mehmetik** [comment]
ekleYardimKaydi içinde çoklu response yapısı rewrite yapılarak aşıldı. tüm route içindeki try'ler zorla catche düşürüldü ve sistemin kesinti yapıp yapmadığı kontrol edildi. Şuan için son güncelleme ile sorunsuz görünmekte.

**Comment by mehmetik** [comment]
Son kontrollerde sorun görülmemektedir. kapatıyorum.
